In [1]:
import cv2

In [2]:
galaxyimg= cv2.imread('D:\Python_Projects\OpenCV_Test\galaxy.jpg',0)

In [3]:
type(galaxyimg)

numpy.ndarray

In [4]:
print(galaxyimg)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [5]:
print(galaxyimg.shape)
print(galaxyimg.ndim)

(1485, 990)
2


In [6]:
resized_img= cv2.resize(galaxyimg, (int(galaxyimg.shape[1]/2), int(galaxyimg.shape[0]/2)))

In [7]:
cv2.imshow("Galaxy", resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
cv2.imwrite("D:\Python_Projects\OpenCV_Test\Galaxy_Resized.jpg", resized_img)

True

In [9]:
import glob

In [19]:
import os

In [20]:
os.mkdir('D:\Python_Projects\OpenCV_Test\ResizedImages')

In [10]:
images= glob.glob('D:\Python_Projects\OpenCV_Test\*.jpg')

In [24]:
for picture in images:
    img= cv2.imread(picture,0)
    resized= cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))
    cv2.imshow(picture.split('\\')[-1], resized)
    cv2.waitKey(1000)
    cv2.destroyAllWindows()
    new_name= 'resized_'+picture.split('\\')[-1]
    save_path= "D:\Python_Projects\OpenCV_Test\ResizedImages"
    cv2.imwrite(os.path.join(save_path, new_name), resized)
    

print('End')

End
